# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tws_pb2 as tws__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tws_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TWSAgentStub(object):
    """TWS Agent Service - gRPC interface for Interactive Brokers TWS API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/twsagent.TWSAgent/Connect',
                request_serializer=tws__pb2.ConnectRequest.SerializeToString,
                response_deserializer=tws__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/twsagent.TWSAgent/Disconnect',
                request_serializer=tws__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=tws__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.GetContractDetails = channel.unary_unary(
                '/twsagent.TWSAgent/GetContractDetails',
                request_serializer=tws__pb2.ContractDetailsRequest.SerializeToString,
                response_deserializer=tws__pb2.ContractDetailsResponse.FromString,
                _registered_method=True)
        self.GetHistoricalData = channel.unary_unary(
                '/twsagent.TWSAgent/GetHistoricalData',
                request_serializer=tws__pb2.HistoricalDataRequest.SerializeToString,
                response_deserializer=tws__pb2.HistoricalDataResponse.FromString,
                _registered_method=True)
        self.GetHistoricalTicks = channel.unary_unary(
                '/twsagent.TWSAgent/GetHistoricalTicks',
                request_serializer=tws__pb2.HistoricalTicksRequest.SerializeToString,
                response_deserializer=tws__pb2.HistoricalTicksResponse.FromString,
                _registered_method=True)
        self.GetWshMetaData = channel.unary_unary(
                '/twsagent.TWSAgent/GetWshMetaData',
                request_serializer=tws__pb2.WshMetaDataRequest.SerializeToString,
                response_deserializer=tws__pb2.WshMetaDataResponse.FromString,
                _registered_method=True)
        self.GetWshEventData = channel.unary_unary(
                '/twsagent.TWSAgent/GetWshEventData',
                request_serializer=tws__pb2.WshEventDataRequest.SerializeToString,
                response_deserializer=tws__pb2.WshEventDataResponse.FromString,
                _registered_method=True)
        self.GetOptionChain = channel.unary_unary(
                '/twsagent.TWSAgent/GetOptionChain',
                request_serializer=tws__pb2.OptionChainRequest.SerializeToString,
                response_deserializer=tws__pb2.OptionChainResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/twsagent.TWSAgent/GetPositions',
                request_serializer=tws__pb2.PositionsRequest.SerializeToString,
                response_deserializer=tws__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetCompletedOrders = channel.unary_unary(
                '/twsagent.TWSAgent/GetCompletedOrders',
                request_serializer=tws__pb2.CompletedOrdersRequest.SerializeToString,
                response_deserializer=tws__pb2.CompletedOrdersResponse.FromString,
                _registered_method=True)
        self.GetScannerParameters = channel.unary_unary(
                '/twsagent.TWSAgent/GetScannerParameters',
                request_serializer=tws__pb2.ScannerParametersRequest.SerializeToString,
                response_deserializer=tws__pb2.ScannerParametersResponse.FromString,
                _registered_method=True)
        self.RunMarketScanner = channel.unary_unary(
                '/twsagent.TWSAgent/RunMarketScanner',
                request_serializer=tws__pb2.MarketScannerRequest.SerializeToString,
                response_deserializer=tws__pb2.MarketScannerResponse.FromString,
                _registered_method=True)
        self.StreamMarketData = channel.unary_stream(
                '/twsagent.TWSAgent/StreamMarketData',
                request_serializer=tws__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=tws__pb2.MarketDataTick.FromString,
                _registered_method=True)
        self.GetWatchlist = channel.unary_unary(
                '/twsagent.TWSAgent/GetWatchlist',
                request_serializer=tws__pb2.WatchlistRequest.SerializeToString,
                response_deserializer=tws__pb2.WatchlistResponse.FromString,
                _registered_method=True)


class TWSAgentServicer(object):
    """TWS Agent Service - gRPC interface for Interactive Brokers TWS API
    """

    def Connect(self, request, context):
        """Connection management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContractDetails(self, request, context):
        """Contract information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalData(self, request, context):
        """Historical data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalTicks(self, request, context):
        """Historical ticks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWshMetaData(self, request, context):
        """Wall Street Horizon corporate events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWshEventData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionChain(self, request, context):
        """Option chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Portfolio positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletedOrders(self, request, context):
        """Order history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScannerParameters(self, request, context):
        """Market scanner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMarketScanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMarketData(self, request, context):
        """Real-time market data streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWatchlist(self, request, context):
        """Watchlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TWSAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=tws__pb2.ConnectRequest.FromString,
                    response_serializer=tws__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=tws__pb2.DisconnectRequest.FromString,
                    response_serializer=tws__pb2.DisconnectResponse.SerializeToString,
            ),
            'GetContractDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContractDetails,
                    request_deserializer=tws__pb2.ContractDetailsRequest.FromString,
                    response_serializer=tws__pb2.ContractDetailsResponse.SerializeToString,
            ),
            'GetHistoricalData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalData,
                    request_deserializer=tws__pb2.HistoricalDataRequest.FromString,
                    response_serializer=tws__pb2.HistoricalDataResponse.SerializeToString,
            ),
            'GetHistoricalTicks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalTicks,
                    request_deserializer=tws__pb2.HistoricalTicksRequest.FromString,
                    response_serializer=tws__pb2.HistoricalTicksResponse.SerializeToString,
            ),
            'GetWshMetaData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWshMetaData,
                    request_deserializer=tws__pb2.WshMetaDataRequest.FromString,
                    response_serializer=tws__pb2.WshMetaDataResponse.SerializeToString,
            ),
            'GetWshEventData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWshEventData,
                    request_deserializer=tws__pb2.WshEventDataRequest.FromString,
                    response_serializer=tws__pb2.WshEventDataResponse.SerializeToString,
            ),
            'GetOptionChain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionChain,
                    request_deserializer=tws__pb2.OptionChainRequest.FromString,
                    response_serializer=tws__pb2.OptionChainResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=tws__pb2.PositionsRequest.FromString,
                    response_serializer=tws__pb2.PositionsResponse.SerializeToString,
            ),
            'GetCompletedOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletedOrders,
                    request_deserializer=tws__pb2.CompletedOrdersRequest.FromString,
                    response_serializer=tws__pb2.CompletedOrdersResponse.SerializeToString,
            ),
            'GetScannerParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScannerParameters,
                    request_deserializer=tws__pb2.ScannerParametersRequest.FromString,
                    response_serializer=tws__pb2.ScannerParametersResponse.SerializeToString,
            ),
            'RunMarketScanner': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMarketScanner,
                    request_deserializer=tws__pb2.MarketScannerRequest.FromString,
                    response_serializer=tws__pb2.MarketScannerResponse.SerializeToString,
            ),
            'StreamMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMarketData,
                    request_deserializer=tws__pb2.MarketDataRequest.FromString,
                    response_serializer=tws__pb2.MarketDataTick.SerializeToString,
            ),
            'GetWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWatchlist,
                    request_deserializer=tws__pb2.WatchlistRequest.FromString,
                    response_serializer=tws__pb2.WatchlistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twsagent.TWSAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twsagent.TWSAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TWSAgent(object):
    """TWS Agent Service - gRPC interface for Interactive Brokers TWS API
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/Connect',
            tws__pb2.ConnectRequest.SerializeToString,
            tws__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/Disconnect',
            tws__pb2.DisconnectRequest.SerializeToString,
            tws__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContractDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetContractDetails',
            tws__pb2.ContractDetailsRequest.SerializeToString,
            tws__pb2.ContractDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetHistoricalData',
            tws__pb2.HistoricalDataRequest.SerializeToString,
            tws__pb2.HistoricalDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetHistoricalTicks',
            tws__pb2.HistoricalTicksRequest.SerializeToString,
            tws__pb2.HistoricalTicksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWshMetaData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetWshMetaData',
            tws__pb2.WshMetaDataRequest.SerializeToString,
            tws__pb2.WshMetaDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWshEventData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetWshEventData',
            tws__pb2.WshEventDataRequest.SerializeToString,
            tws__pb2.WshEventDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOptionChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetOptionChain',
            tws__pb2.OptionChainRequest.SerializeToString,
            tws__pb2.OptionChainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetPositions',
            tws__pb2.PositionsRequest.SerializeToString,
            tws__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompletedOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetCompletedOrders',
            tws__pb2.CompletedOrdersRequest.SerializeToString,
            tws__pb2.CompletedOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScannerParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetScannerParameters',
            tws__pb2.ScannerParametersRequest.SerializeToString,
            tws__pb2.ScannerParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMarketScanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/RunMarketScanner',
            tws__pb2.MarketScannerRequest.SerializeToString,
            tws__pb2.MarketScannerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/twsagent.TWSAgent/StreamMarketData',
            tws__pb2.MarketDataRequest.SerializeToString,
            tws__pb2.MarketDataTick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twsagent.TWSAgent/GetWatchlist',
            tws__pb2.WatchlistRequest.SerializeToString,
            tws__pb2.WatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
